### PR TITLE
Add dts declaration

### PR DESCRIPTION
**Pull request by octref**
This adds dts declaration so when importing it we could have IntelliSense on the exported functions.

Still need to publish them to npm with `emmetHelper.d.ts` in `out` and this updated `package.json` though.

### CODE REVIEW

**Comment by octref** [comment]
@ramya-rao-a Would you mind publishing type definition with the module? Also `emmetHelperTest` is unnecessary in the published module.

**Review by ramya-rao-a — APPROVED** [review]

**Comment by ramya-rao-a** [comment]
@octref There is an issue with publishing the d.ts

The Emmet helper uses types from the `vscode-languageserver-types`. So if you were to use the d.ts for your vue language server, everything would work just fine.

But the emmet extension on the other hand is using the types from `vscode.d.ts`. I get all sorts of build error due to the incompatibility between the types of `vscode.d.ts` vs `vscode-languageserver-types`

As a middle ground, I am thinking of checking in the d.ts file in the repo but not publish it in the npm package. 

Do you have any better ideas?

**Comment by octref** [comment]
Um, I thought the emmet extension would be similar to html extension that's also using `vscode-languageserver-types`?

**Comment by ramya-rao-a** [comment]
@octref No... emmet is a normal extension using [completion provider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#CompletionItemProvider)

**Comment by octref** [comment]
Guess you can take the middle ground for now. I'll be back to Seattle in 10 days and we can discuss for a better solution.

**Pull request merged**
