### PR TITLE
feat: Add button type=button

### PR DESCRIPTION
**Pull request by tyankatsu0105**
Add type for button
https://html.spec.whatwg.org/multipage/input.html#button-state-(type=button)

### CODE REVIEW

**Comment by tyankatsu0105** [comment]
Hi! @ramya-rao-a 
This repository still active?

**Comment by tyankatsu0105** [comment]
@octref 
👋

**Comment by octref** [comment]
I can't see this abbreviation in https://docs.emmet.io/. Where is it from?

**Comment by ramya-rao-a** [comment]
`expand-full.js` is a generated file.
This change should be made to https://github.com/emmetio/snippets/blob/master/html.json, have a new version of that package released, and then update `vscode-emmet-helper` to use it

**Comment by tyankatsu0105** [comment]
OK! 
Thanks !!!

**Comment by tyankatsu0105** [comment]
Merged!! XD
https://github.com/emmetio/snippets/pull/17

**Comment by octref** [comment]
Thanks, I'll pull it from upstream sometime.

**Pull request closed without merging**
